<?php
declare(strict_types=1);

// LatlngGeocoding SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

LatlngGeocodingUtility::setRegistrar(function (LatlngGeocodingUtility $u): void {
    $u->clean = [LatlngGeocodingClean::class, 'call'];
    $u->done = [LatlngGeocodingDone::class, 'call'];
    $u->make_error = [LatlngGeocodingMakeError::class, 'call'];
    $u->feature_add = [LatlngGeocodingFeatureAdd::class, 'call'];
    $u->feature_hook = [LatlngGeocodingFeatureHook::class, 'call'];
    $u->feature_init = [LatlngGeocodingFeatureInit::class, 'call'];
    $u->fetcher = [LatlngGeocodingFetcher::class, 'call'];
    $u->make_fetch_def = [LatlngGeocodingMakeFetchDef::class, 'call'];
    $u->make_context = [LatlngGeocodingMakeContext::class, 'call'];
    $u->make_options = [LatlngGeocodingMakeOptions::class, 'call'];
    $u->make_request = [LatlngGeocodingMakeRequest::class, 'call'];
    $u->make_response = [LatlngGeocodingMakeResponse::class, 'call'];
    $u->make_result = [LatlngGeocodingMakeResult::class, 'call'];
    $u->make_point = [LatlngGeocodingMakePoint::class, 'call'];
    $u->make_spec = [LatlngGeocodingMakeSpec::class, 'call'];
    $u->make_url = [LatlngGeocodingMakeUrl::class, 'call'];
    $u->param = [LatlngGeocodingParam::class, 'call'];
    $u->prepare_auth = [LatlngGeocodingPrepareAuth::class, 'call'];
    $u->prepare_body = [LatlngGeocodingPrepareBody::class, 'call'];
    $u->prepare_headers = [LatlngGeocodingPrepareHeaders::class, 'call'];
    $u->prepare_method = [LatlngGeocodingPrepareMethod::class, 'call'];
    $u->prepare_params = [LatlngGeocodingPrepareParams::class, 'call'];
    $u->prepare_path = [LatlngGeocodingPreparePath::class, 'call'];
    $u->prepare_query = [LatlngGeocodingPrepareQuery::class, 'call'];
    $u->graphql_body = [LatlngGeocodingGraphql::class, 'body'];
    $u->graphql_errors = [LatlngGeocodingGraphql::class, 'errors'];
    $u->result_basic = [LatlngGeocodingResultBasic::class, 'call'];
    $u->result_body = [LatlngGeocodingResultBody::class, 'call'];
    $u->result_headers = [LatlngGeocodingResultHeaders::class, 'call'];
    $u->transform_request = [LatlngGeocodingTransformRequest::class, 'call'];
    $u->transform_response = [LatlngGeocodingTransformResponse::class, 'call'];
});
